[env:tars]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    bblanchon/ArduinoJson
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

build_flags =
    -DCORE_DEBUG_LEVEL=0
